name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/python-publish.yml@python-publish
    # with:
    #   test_pypi: true
    secrets:
      # PYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
